version: '3.4'

services:
  nginx:
    image: nginx
    container_name: magento_nginx
    restart: on-failure
    depends_on:
      - php-fpm
    volumes:
      - ./magento2:/usr/share/nginx/html
      - ./nginx/magento.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80

  php-fpm:
    build: ./php
    container_name: magento_php
    command: ["magento-init", "php-fpm"]
    restart: on-failure
    working_dir: /usr/share/nginx/html
    environment:
      MAGENTO_PUBLIC_KEY: ${MAGENTO_PUBLIC_KEY}
      MAGENTO_SECRET_KEY: ${MAGENTO_SECRET_KEY}
    volumes:
      - ./magento2:/usr/share/nginx/html
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/conf.d/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf

  mysql:
    image: mysql:5.7
    container_name: magento_mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-magento}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-magento}
      MYSQL_USER: ${MYSQL_MAGENTO_USER:-magento}
      MYSQL_PASSWORD: ${MYSQL_MAGENTO_PASSWORD:-magento}

  adminer:
    image: adminer
    restart: on-failure
    environment:
      ADMINER_DEFAULT_SERVER: magento_mysql
    ports:
      - 9000:8080