version: '3.4'

services:
  nginx:
    image: nginx
    container_name: magento_nginx
    restart: on-failure
    depends_on:
      - php-fpm
    volumes:
      - ./magento2:/usr/share/nginx/html
      - ./nginx/magento.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80

  php-fpm:
    build: ./php
    container_name: magento_php
    command: ["magento-init", "php-fpm"]
    restart: on-failure
    environment:
      MAGENTO_PUBLIC_KEY: ${MAGENTO_PUBLIC_KEY}
      MAGENTO_SECRET_KEY: ${MAGENTO_SECRET_KEY}
      MAGENTO_BASE_URL: ${MAGENTO_BASE_URL}
      MAGENTO_DB_NAME: ${MYSQL_DATABASE:-magento}
      MAGENTO_DB_USER: ${MYSQL_MAGENTO_USER:-magento}
      MAGENTO_DB_PASSWORD: ${MYSQL_MAGENTO_PASSWORD:-magento}
      MAGENTO_BACKEND_FRONTNAME: ${MAGENTO_BACKEND_FRONTNAME}
      MAGENTO_ADMIN_FIRSTNAME: ${MAGENTO_ADMIN_FIRSTNAME}
      MAGENTO_ADMIN_LASTNAME: ${MAGENTO_ADMIN_LASTNAME}
      MAGENTO_ADMIN_EMAIL: ${MAGENTO_ADMIN_EMAIL}
      MAGENTO_ADMIN_USER: ${MAGENTO_ADMIN_USER}
      MAGENTO_ADMIN_PASSWORD: ${MAGENTO_ADMIN_PASSWORD}
      MAGENTO_LANGUAGE: ${MAGENTO_LANGUAGE}
      MAGENTO_CURRENCY: ${MAGENTO_CURRENCY}
    volumes:
      - ./magento2:/var/www/html
      - ./php/conf.d/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf

  mysql:
    image: mysql:5.7
    container_name: magento_mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-magento}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-magento}
      MYSQL_USER: ${MYSQL_MAGENTO_USER:-magento}
      MYSQL_PASSWORD: ${MYSQL_MAGENTO_PASSWORD:-magento}
